["0.bea29d45-274d-4a50-91ec-8ca09897ce4d"]
diffuseColor = [1.0, 1.0, 1.0, 1.0]
relativeLocation = [0.0, 0.0, 0.0]
sDiffuseTexture = ""
sCustomVertexShader = ""
sCustomFragmentShader = ""
sNodeName = "Torus"
relativeRotation = [0.0, 0.0, 0.0]
opacity = 1.0
relativeScale = [1.0, 1.0, 1.0]
bIsVisible = true
bEnableTransparency = false

