["0.bea29d45-274d-4a50-91ec-8ca09897ce4d"]
materialDiffuseColor = [1.0, 1.0, 1.0, 1.0]
relativeLocation = [0.0, 0.0, 0.0]
materialDiffuseTexture = ""
materialCustomVertexShader = ""
materialCustomFragmentShader = ""
sNodeName = "arrow"
relativeRotation = [0.0, 0.0, 0.0]
materialOpacity = 1.0
relativeScale = [1.0, 1.0, 1.0]
bIsVisible = true
materialTransparencyEnabled = false

